import Head from "next/head";
import CaruselVideos from "@/components/carusel";

export default function Home() {
  return (
    <>
      <Head>
        <title>Carusel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CaruselVideos />
    </>
  );
}
